# Generated by Django 3.2.7 on 2021-09-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Finished'), (3, 'Failed')], default=0)),
            ],
            options={
                'verbose_name': 'Contact Upload',
                'verbose_name_plural': 'Contact Uploads',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('has_mx_records', models.BooleanField(default=None, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactupload')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('email',),
            },
        ),
    ]
